**CASE 1: Without PCA**

In [99]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [100]:
df = pd.read_csv("/content/breast-cancer.csv")

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [102]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [103]:
#Drop ID
df.drop(columns=['id'], inplace=True)

#Encode target
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [104]:
#Scaling + split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [105]:
cov_matrix=np.cov(X_train.T)
cov_matrix

array([[ 1.00841254,  0.2995942 ,  1.00253204,  1.01111003,  0.13389721,
         0.44549491,  0.64239895,  0.79260344,  0.15985525, -0.36868514,
         0.70845095, -0.06361934,  0.69006112,  0.77690115, -0.2063214 ,
         0.15621511,  0.17610741,  0.33755715, -0.05470671, -0.07733353,
         0.96609436,  0.27690276,  0.95387212,  0.94820359,  0.08513255,
         0.34206754,  0.48499403,  0.70016541,  0.17562161, -0.0539932 ],
       [ 0.2995942 ,  0.9616613 ,  0.30544487,  0.29745154,  0.00959337,
         0.22887955,  0.28475328,  0.28277207,  0.10669752, -0.0756814 ,
         0.28040667,  0.37289183,  0.29025531,  0.26011456,  0.03063436,
         0.21082466,  0.15617643,  0.20536746,  0.0276119 ,  0.04454648,
         0.32768557,  0.86990512,  0.33536433,  0.31806668,  0.08419462,
         0.25700589,  0.26732972,  0.29373954,  0.1086933 ,  0.0767202 ],
       [ 1.00253204,  0.30544487,  1.00098136,  1.00691911,  0.16979297,
         0.49443638,  0.67964361,  0.818273  ,  0.19285488, -0.31785304,
         0.71960749, -0.05177998,  0.70824928,  0.78483708, -0.18371802,
         0.20098703,  0.21028923,  0.37020583, -0.03660331, -0.03990853,
         0.96244342,  0.28254774,  0.95579395,  0.94560355,  0.11627625,
         0.38219609,  0.51970045,  0.72557376,  0.19614998, -0.0110691 ],
       [ 1.01111003,  0.29745154,  1.00691911,  1.04172677,  0.14951909,
         0.44824877,  0.66503251,  0.80728172,  0.16278837, -0.33919395,
         0.77914828, -0.03673005,  0.75997735,  0.86618251, -0.14548911,
         0.1700672 ,  0.19529587,  0.34148374, -0.02855368, -0.04810519,
         0.97261522,  0.2672589 ,  0.96133028,  0.98203995,  0.09705681,
         0.32730542,  0.4796498 ,  0.68949475,  0.15092191, -0.05286682],
       [ 0.13389721,  0.00959337,  0.16979297,  0.14951909,  0.95976995,
         0.6348339 ,  0.49637951,  0.51821574,  0.51532321,  0.593464  ,
         0.28589004,  0.09585689,  0.27404494,  0.23912064,  0.32785767,
         0.28836462,  0.23393015,  0.35126144,  0.17464023,  0.27353818,
         0.18109405,  0.06053394,  0.20503795,  0.18259017,  0.79263236,
         0.4443013 ,  0.41470649,  0.47956708,  0.36034081,  0.49763871],
       [ 0.44549491,  0.22887955,  0.49443638,  0.44824877,  0.6348339 ,
         0.94183035,  0.8260166 ,  0.76682058,  0.59203671,  0.5636671 ,
         0.47232029,  0.0981358 ,  0.52426235,  0.43114332,  0.18535788,
         0.71462636,  0.56246186,  0.63825733,  0.23056655,  0.49934573,
         0.47183557,  0.23668102,  0.52435755,  0.45527841,  0.55466282,
         0.78947922,  0.75378288,  0.76086753,  0.47210708,  0.64251402],
       [ 0.64239895,  0.28475328,  0.67964361,  0.66503251,  0.49637951,
         0.8260166 ,  0.95497769,  0.87359918,  0.49816617,  0.32266088,
         0.63021541,  0.1169191 ,  0.65203378,  0.62411835,  0.14201258,
         0.63142817,  0.67492921,  0.66274392,  0.18520713,  0.45420151,
         0.64637162,  0.28080591,  0.68293394,  0.6452562 ,  0.43151243,
         0.67419801,  0.81420796,  0.80766051,  0.37982762,  0.46652163],
       [ 0.79260344,  0.28277207,  0.818273  ,  0.80728172,  0.51821574,
         0.76682058,  0.87359918,  0.94620391,  0.45981869,  0.13571227,
         0.69297645,  0.05422352,  0.69602147,  0.69568427,  0.06022815,
         0.43978373,  0.42618624,  0.58498362,  0.12172201,  0.23070027,
         0.79458949,  0.28465108,  0.81397905,  0.78444378,  0.43749099,
         0.59031811,  0.69864752,  0.8582352 ,  0.37071386,  0.31831904],
       [ 0.15985525,  0.10669752,  0.19285488,  0.16278837,  0.51532321,
         0.59203671,  0.49816617,  0.45981869,  0.96244163,  0.46183574,
         0.29342267,  0.18456964,  0.30447601,  0.22221036,  0.18574813,
         0.44420465,  0.36423127,  0.42623579,  0.41352353,  0.36414104,
         0.19321211,  0.12814767,  0.2250222 ,  0.18324616,  0.40970577,
         0.46456611,  0.433057  ,  0.45106913,  0.67165277,  0.43861648],
       [-0.36868514, -0.0756814 , -0.31785304, -0.33919395,  0.593464  ,
         0.5636671 ,  0.32266088,  0.13571227,  0.46183574,  1.05579124,
        -0.03745172,  0.18191637,  0.01026291, -0.13050696,  0.44549907,
         0.56673479,  0.46617124,  0.37187333,  0.29819705,  0.71982158,
        -0.30535206, -0.05698393, -0.25409728, -0.28005714,  0.5271188 ,
         0.44420196,  0.32817009,  0.16239987,  0.28880029,  0.78387159],
       [ 0.70845095,  0.28040667,  0.71960749,  0.77914828,  0.28589004,
         0.47232029,  0.63021541,  0.69297645,  0.29342267, -0.03745172,
         1.0989412 ,  0.24570722,  1.06892601,  1.07244771,  0.17878461,
         0.33407363,  0.3461626 ,  0.51389   ,  0.25732432,  0.20924093,
         0.73216056,  0.19055662,  0.73159432,  0.77872973,  0.11139074,
         0.24548957,  0.36405601,  0.5120714 ,  0.06511046,  0.00662041],
       [-0.06361934,  0.37289183, -0.05177998, -0.03673005,  0.09585689,
         0.0981358 ,  0.1169191 ,  0.05422352,  0.18456964,  0.18191637,
         0.24570722,  0.88788343,  0.25840503,  0.14656856,  0.39627834,
         0.27838855,  0.25985608,  0.28929031,  0.37814362,  0.31387651,
        -0.07657658,  0.40229557, -0.06444996, -0.0544205 , -0.04924597,
        -0.03637376, -0.01859953, -0.0647622 , -0.08925726, -0.00528918],
       [ 0.69006112,  0.29025531,  0.70824928,  0.75997735,  0.27404494,
         0.52426235,  0.65203378,  0.69602147,  0.30447601,  0.01026291,
         1.06892601,  0.25840503,  1.09526283,  1.05358645,  0.16859787,
         0.40834236,  0.38160135,  0.56656593,  0.28275844,  0.24284512,
         0.6999108 ,  0.19578894,  0.71938882,  0.74362283,  0.09395322,
         0.30249776,  0.39939118,  0.52969471,  0.07290873,  0.05090927],
       [ 0.77690115,  0.26011456,  0.78483708,  0.86618251,  0.23912064,
         0.43114332,  0.62411835,  0.69568427,  0.22221036, -0.13050696,
         1.07244771,  0.14656856,  1.05358645,  1.15675108,  0.10761767,
         0.26507336,  0.27901503,  0.41034892,  0.16129717,  0.11272819,
         0.78224906,  0.18583878,  0.78093517,  0.85345782,  0.10247735,
         0.23889831,  0.36727279,  0.52047264,  0.04226056, -0.02915949],
       [-0.2063214 ,  0.03063436, -0.18371802, -0.14548911,  0.32785767,
         0.18535788,  0.14201258,  0.06022815,  0.18574813,  0.44549907,
         0.17878461,  0.39627834,  0.16859787,  0.10761767,  1.07751717,
         0.41055483,  0.33021893,  0.37536326,  0.38461567,  0.48881114,
        -0.21876056, -0.0705464 , -0.20134954, -0.16448267,  0.32119614,
        -0.01472397, -0.02067849, -0.07046315, -0.1392265 ,  0.13981477],
       [ 0.15621511,  0.21082466,  0.20098703,  0.1700672 ,  0.28836462,
         0.71462636,  0.63142817,  0.43978373,  0.44420465,  0.56673479,
         0.33407363,  0.27838855,  0.40834236,  0.26507336,  0.41055483,
         1.01150546,  0.80680119,  0.75218878,  0.39971521,  0.79944928,
         0.15244135,  0.15215495,  0.21171964,  0.1549931 ,  0.21136272,
         0.64128164,  0.58965066,  0.43890709,  0.26093497,  0.56376917],
       [ 0.17610741,  0.15617643,  0.21028923,  0.19529587,  0.23393015,
         0.56246186,  0.67492921,  0.42618624,  0.36423127,  0.46617124,
         0.3461626 ,  0.25985608,  0.38160135,  0.27901503,  0.33021893,
         0.80680119,  0.9930894 ,  0.791895  ,  0.2960503 ,  0.79166253,
         0.16298921,  0.10172927,  0.20488857,  0.16994075,  0.14714609,
         0.44430883,  0.59232928,  0.4057696 ,  0.15270994,  0.42179549],
       [ 0.33755715,  0.20536746,  0.37020583,  0.34148374,  0.35126144,
         0.63825733,  0.66274392,  0.58498362,  0.42623579,  0.37187333,
         0.51389   ,  0.28929031,  0.56656593,  0.41034892,  0.37536326,
         0.75218878,  0.791895  ,  1.02254374,  0.32730742,  0.649404  ,
         0.32028902,  0.10886871,  0.35965319,  0.31226904,  0.18933173,
         0.42672349,  0.51241867,  0.56499554,  0.12772436,  0.31223212],
       [-0.05470671,  0.0276119 , -0.03660331, -0.02855368,  0.17464023,
         0.23056655,  0.18520713,  0.12172201,  0.41352353,  0.29819705,
         0.25732432,  0.37814362,  0.28275844,  0.16129717,  0.38461567,
         0.39971521,  0.2960503 ,  0.32730742,  0.94208983,  0.35176439,
        -0.08461885, -0.05755568, -0.06349226, -0.07582767, -0.02244645,
         0.09324909,  0.05586795,  0.01557774,  0.38871066,  0.09573303],
       [-0.07733353,  0.04454648, -0.03990853, -0.04810519,  0.27353818,
         0.49934573,  0.45420151,  0.23070027,  0.36414104,  0.71982158,
         0.20924093,  0.31387651,  0.24284512,  0.11272819,  0.48881114,
         0.79944928,  0.79166253,  0.649404  ,  0.35176439,  1.00543438,
        -0.07145856, -0.01478242, -0.03060993, -0.04910151,  0.16823823,
         0.37003872,  0.37390307,  0.19862936,  0.10222797,  0.58803248],
       [ 0.96609436,  0.32768557,  0.96244342,  0.97261522,  0.18109405,
         0.47183557,  0.64637162,  0.79458949,  0.19321211, -0.30535206,
         0.73216056, -0.07657658,  0.6999108 ,  0.78224906, -0.21876056,
         0.15244135,  0.16298921,  0.32028902, -0.08461885, -0.07145856,
         0.98790133,  0.33960842,  0.97307455,  0.98023418,  0.18794657,
         0.40229968,  0.52821929,  0.74211745,  0.2525298 ,  0.03422968],
       [ 0.27690276,  0.86990512,  0.28254774,  0.2672589 ,  0.06053394,
         0.23668102,  0.28080591,  0.28465108,  0.12814767, -0.05698393,
         0.19055662,  0.40229557,  0.19578894,  0.18583878, -0.0705464 ,
         0.15215495,  0.10172927,  0.10886871, -0.05755568, -0.01478242,
         0.33960842,  0.96024893,  0.34597588,  0.3234255 ,  0.22968603,
         0.34021322,  0.33710866,  0.36324226,  0.24540776,  0.17734954],
       [ 0.95387212,  0.33536433,  0.95579395,  0.96133028,  0.20503795,
         0.52435755,  0.68293394,  0.81397905,  0.2250222 , -0.25409728,
         0.73159432, -0.06444996,  0.71938882,  0.78093517, -0.20134954,
         0.21171964,  0.20488857,  0.35965319, -0.06349226, -0.03060993,
         0.97307455,  0.34597588,  0.97103476,  0.96557624,  0.20788414,
         0.45440073,  0.56903451,  0.76673174,  0.27399401,  0.08134591],
       [ 0.94820359,  0.31806668,  0.94560355,  0.98203995,  0.18259017,
         0.45527841,  0.6452562 ,  0.78444378,  0.18324616, -0.28005714,
         0.77872973, -0.0544205 ,  0.74362283,  0.85345782, -0.16448267,
         0.1549931 ,  0.16994075,  0.31226904, -0.07582767, -0.04910151,
         0.98023418,  0.3234255 ,  0.96557624,  1.00668221,  0.1887485 ,
         0.37259344,  0.50547655,  0.71090149,  0.21137657,  0.02566891],
       [ 0.08513255,  0.08419462,  0.11627625,  0.09705681,  0.79263236,
         0.55466282,  0.43151243,  0.43749099,  0.40970577,  0.5271188 ,
         0.11139074, -0.04924597,  0.09395322,  0.10247735,  0.32119614,
         0.21136272,  0.14714609,  0.18933173, -0.02244645,  0.16823823,
         0.18794657,  0.22968603,  0.20788414,  0.1887485 ,  1.01856696,
         0.55386819,  0.50564223,  0.54302589,  0.48340875,  0.62464624],
       [ 0.34206754,  0.25700589,  0.38219609,  0.32730542,  0.4443013 ,
         0.78947922,  0.67419801,  0.59031811,  0.46456611,  0.44420196,
         0.24548957, -0.03637376,  0.30249776,  0.23889831, -0.01472397,
         0.64128164,  0.44430883,  0.42672349,  0.09324909,  0.37003872,
         0.40229968,  0.34021322,  0.45440073,  0.37259344,  0.55386819,
         0.89386219,  0.79085375,  0.73071381,  0.58596959,  0.72894862],
       [ 0.48499403,  0.26732972,  0.51970045,  0.4796498 ,  0.41470649,
         0.75378288,  0.81420796,  0.69864752,  0.433057  ,  0.32817009,
         0.36405601, -0.01859953,  0.39939118,  0.36727279, -0.02067849,
         0.58965066,  0.59232928,  0.51241867,  0.05586795,  0.37390307,
         0.52821929,  0.33710866,  0.56903451,  0.50547655,  0.50564223,
         0.79085375,  0.88544765,  0.79036849,  0.50292439,  0.61113095],
       [ 0.70016541,  0.29373954,  0.72557376,  0.68949475,  0.47956708,
         0.76086753,  0.80766051,  0.8582352 ,  0.45106913,  0.16239987,
         0.5120714 , -0.0647622 ,  0.52969471,  0.52047264, -0.07046315,
         0.43890709,  0.4057696 ,  0.56499554,  0.01557774,  0.19862936,
         0.74211745,  0.36324226,  0.76673174,  0.71090149,  0.54302589,
         0.73071381,  0.79036849,  0.9462611 ,  0.51681606,  0.46966056],
       [ 0.17562161,  0.1086933 ,  0.19614998,  0.15092191,  0.36034081,
         0.47210708,  0.37982762,  0.37071386,  0.67165277,  0.28880029,
         0.06511046, -0.08925726,  0.07290873,  0.04226056, -0.1392265 ,
         0.26093497,  0.15270994,  0.12772436,  0.38871066,  0.10222797,
         0.2525298 ,  0.24540776,  0.27399401,  0.21137657,  0.48340875,
         0.58596959,  0.50292439,  0.51681606,  1.0164073 ,  0.51536721],
       [-0.0539932 ,  0.0767202 , -0.0110691 , -0.05286682,  0.49763871,
         0.64251402,  0.46652163,  0.31831904,  0.43861648,  0.78387159,
         0.00662041, -0.00528918,  0.05090927, -0.02915949,  0.13981477,
         0.56376917,  0.42179549,  0.31223212,  0.09573303,  0.58803248,
         0.03422968,  0.17734954,  0.08134591,  0.02566891,  0.62464624,
         0.72894862,  0.61113095,  0.46966056,  0.51536721,  0.94238952]])

In [106]:
eigen_values,eigen_vectors=np.linalg.eig(cov_matrix)
eigen_values;

In [107]:
#Model training
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [108]:
y_pred = model.predict(X_test)

In [109]:
from sklearn.metrics import classification_report
#Model Report
acc = accuracy_score(y_test, y_pred)
print(f"WITHOUT PCA -> Accuracy={acc:.4f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

WITHOUT PCA -> Accuracy=0.9825
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       108
           1       0.97      0.98      0.98        63

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

**CASE 2: Logistic Regression WITH PCA**

In [110]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [111]:
df = pd.read_csv("/content/breast-cancer.csv")

#Drop ID column
df.drop(columns=['id'], inplace=True)

#Encode target variable
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

In [112]:
#Split Features and Target
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [113]:
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [114]:
#Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

**PCA CASE 1: PC1 only**

In [115]:
pca_1 = PCA(n_components=1)

X_train_pca1 = pca_1.fit_transform(X_train_scaled)
X_test_pca1 = pca_1.transform(X_test_scaled)

model_1 = LogisticRegression(max_iter=5000)
model_1.fit(X_train_pca1, y_train)

y_pred_1 = model_1.predict(X_test_pca1)
acc_1 = accuracy_score(y_test, y_pred_1)

explained_var = pca_1.explained_variance_ratio_
print("Variance: ", explained_var)

print("Accuracy using PC1:", acc_1)
print("Model Report")
print(classification_report(y_test, y_pred_1, zero_division=1))

Variance:  [0.4316748]
Accuracy using PC1: 0.9239766081871345
Model Report
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       108
           1       0.90      0.89      0.90        63

    accuracy                           0.92       171
   macro avg       0.92      0.92      0.92       171
weighted avg       0.92      0.92      0.92       171

**PCA CASE 2: PCA1 + PCA2**

In [116]:
pca_2 = PCA(n_components=2)

X_train_pca2 = pca_2.fit_transform(X_train_scaled)
X_test_pca2 = pca_2.transform(X_test_scaled)

explained_var = pca_2.explained_variance_ratio_
print("Variance: ", explained_var)

model_2 = LogisticRegression(max_iter=5000)
model_2.fit(X_train_pca2, y_train)

y_pred_2 = model_2.predict(X_test_pca2)
acc_2 = accuracy_score(y_test, y_pred_2)

print("Accuracy using PC1 + PC2:", acc_2)
print("Model report")
print(classification_report(y_test, y_pred_2, zero_division=1))

Variance:  [0.4316748  0.19845652]
Accuracy using PC1 + PC2: 0.9766081871345029
Model report
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       108
           1       0.97      0.97      0.97        63

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

**PCA CASE 3: PCA1 + PCA2 + PCA3**

In [117]:
pca_3 = PCA(n_components=3)

X_train_pca3 = pca_3.fit_transform(X_train_scaled)
X_test_pca3 = pca_3.transform(X_test_scaled)

explained_var = pca_3.explained_variance_ratio_
print("Variance: ", explained_var)

model_3 = LogisticRegression(max_iter=5000)
model_3.fit(X_train_pca3, y_train)

y_pred_3 = model_3.predict(X_test_pca3)
acc_3 = accuracy_score(y_test, y_pred_3)

print("Accuracy using PC1 + PC2 + PC3:", acc_3)
print("Model Report")
print(classification_report(y_test, y_pred_3, zero_division=1))

Variance:  [0.4316748  0.19845652 0.09733159]
Accuracy using PC1 + PC2 + PC3: 0.9707602339181286
Model Report
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       108
           1       0.97      0.95      0.96        63

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171