In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_breast_cancer

In [2]:
bc = load_breast_cancer()
df = pd.DataFrame(bc.data, columns=bc.feature_names)
df['diagnosis'] = bc.target
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  diagnosis                569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [4]:
df.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,diagnosis
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [5]:
# Features and target
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [6]:
# Scaling + split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [7]:
# Covariance Matrix
cov_matrix = np.cov(X_train.T)
cov_matrix

array([[ 1.00841254,  0.2995942 ,  1.00253204,  1.01111003,  0.13389721,
         0.44549491,  0.64239895,  0.79260344,  0.15985525, -0.36868514,
         0.70845095, -0.06361934,  0.69006112,  0.77690115, -0.2063214 ,
         0.15621511,  0.17610741,  0.33755715, -0.05470671, -0.07733353,
         0.96609436,  0.27690276,  0.95387212,  0.94820359,  0.08513255,
         0.34206754,  0.48499403,  0.70016541,  0.17562161, -0.0539932 ],
       [ 0.2995942 ,  0.9616613 ,  0.30544487,  0.29745154,  0.00959337,
         0.22887955,  0.28475328,  0.28277207,  0.10669752, -0.0756814 ,
         0.28040667,  0.37289183,  0.29025531,  0.26011456,  0.03063436,
         0.21082466,  0.15617643,  0.20536746,  0.0276119 ,  0.04454648,
         0.32768557,  0.86990512,  0.33536433,  0.31806668,  0.08419462,
         0.25700589,  0.26732972,  0.29373954,  0.1086933 ,  0.0767202 ],
       [ 1.00253204,  0.30544487,  1.00098136,  1.00691911,  0.16979297,
         0.49443638,  0.67964361,  0.818273  ,  0.19285488, -0.31785304,
         0.71960749, -0.05177998,  0.70824928,  0.78483708, -0.18371802,
         0.20098703,  0.21028923,  0.37020583, -0.03660331, -0.03990853,
         0.96244342,  0.28254774,  0.95579395,  0.94560355,  0.11627625,
         0.38219609,  0.51970045,  0.72557376,  0.19614998, -0.0110691 ],
       [ 1.01111003,  0.29745154,  1.00691911,  1.04172677,  0.14951909,
         0.44824877,  0.66503251,  0.80728172,  0.16278837, -0.33919395,
         0.77914828, -0.03673005,  0.75997735,  0.86618251, -0.14548911,
         0.1700672 ,  0.19529587,  0.34148374, -0.02855368, -0.04810519,
         0.97261522,  0.2672589 ,  0.96133028,  0.98203995,  0.09705681,
         0.32730542,  0.4796498 ,  0.68949475,  0.15092191, -0.05286682],
       [ 0.13389721,  0.00959337,  0.16979297,  0.14951909,  0.95976995,
         0.6348339 ,  0.49637951,  0.51821574,  0.51532321,  0.593464  ,
         0.28589004,  0.09585689,  0.27404494,  0.23912064,  0.32785767,
         0.28836462,  0.23393015,  0.35126144,  0.17464023,  0.27353818,
         0.18109405,  0.06053394,  0.20503795,  0.18259017,  0.79263236,
         0.4443013 ,  0.41470649,  0.47956708,  0.36034081,  0.49763871],
       [ 0.44549491,  0.22887955,  0.49443638,  0.44824877,  0.6348339 ,
         0.94183035,  0.8260166 ,  0.76682058,  0.59203671,  0.5636671 ,
         0.47232029,  0.0981358 ,  0.52426235,  0.43114332,  0.18535788,
         0.71462636,  0.56246186,  0.63825733,  0.23056655,  0.49934573,
         0.47183557,  0.23668102,  0.52435755,  0.45527841,  0.55466282,
         0.78947922,  0.75378288,  0.76086753,  0.47210708,  0.64251402],
       [ 0.64239895,  0.28475328,  0.67964361,  0.66503251,  0.49637951,
         0.8260166 ,  0.95497769,  0.87359918,  0.49816617,  0.32266088,
         0.63021541,  0.1169191 ,  0.65203378,  0.62411835,  0.14201258,
         0.63142817,  0.67492921,  0.66274392,  0.18520713,  0.45420151,
         0.64637162,  0.28080591,  0.68293394,  0.6452562 ,  0.43151243,
         0.67419801,  0.81420796,  0.80766051,  0.37982762,  0.46652163],
       [ 0.79260344,  0.28277207,  0.818273  ,  0.80728172,  0.51821574,
         0.76682058,  0.87359918,  0.94620391,  0.45981869,  0.13571227,
         0.69297645,  0.05422352,  0.69602147,  0.69568427,  0.06022815,
         0.43978373,  0.42618624,  0.58498362,  0.12172201,  0.23070027,
         0.79458949,  0.28465108,  0.81397905,  0.78444378,  0.43749099,
         0.59031811,  0.69864752,  0.8582352 ,  0.37071386,  0.31831904],
       [ 0.15985525,  0.10669752,  0.19285488,  0.16278837,  0.51532321,
         0.59203671,  0.49816617,  0.45981869,  0.96244163,  0.46183574,
         0.29342267,  0.18456964,  0.30447601,  0.22221036,  0.18574813,
         0.44420465,  0.36423127,  0.42623579,  0.41352353,  0.36414104,
         0.19321211,  0.12814767,  0.2250222 ,  0.18324616,  0.40970577,
         0.46456611,  0.433057  ,  0.45106913,  0.67165277,  0.43861648],
       [-0.36868514, -0.0756814 , -0.31785304, -0.33919395,  0.593464  ,
         0.5636671 ,  0.32266088,  0.13571227,  0.46183574,  1.05579124,
        -0.03745172,  0.18191637,  0.01026291, -0.13050696,  0.44549907,
         0.56673479,  0.46617124,  0.37187333,  0.29819705,  0.71982158,
        -0.30535206, -0.05698393, -0.25409728, -0.28005714,  0.5271188 ,
         0.44420196,  0.32817009,  0.16239987,  0.28880029,  0.78387159],
       [ 0.70845095,  0.28040667,  0.71960749,  0.77914828,  0.28589004,
         0.47232029,  0.63021541,  0.69297645,  0.29342267, -0.03745172,
         1.0989412 ,  0.24570722,  1.06892601,  1.07244771,  0.17878461,
         0.33407363,  0.3461626 ,  0.51389   ,  0.25732432,  0.20924093,
         0.73216056,  0.19055662,  0.73159432,  0.77872973,  0.11139074,
         0.24548957,  0.36405601,  0.5120714 ,  0.06511046,  0.00662041],
       [-0.06361934,  0.37289183, -0.05177998, -0.03673005,  0.09585689,
         0.0981358 ,  0.1169191 ,  0.05422352,  0.18456964,  0.18191637,
         0.24570722,  0.88788343,  0.25840503,  0.14656856,  0.39627834,
         0.27838855,  0.25985608,  0.28929031,  0.37814362,  0.31387651,
        -0.07657658,  0.40229557, -0.06444996, -0.0544205 , -0.04924597,
        -0.03637376, -0.01859953, -0.0647622 , -0.08925726, -0.00528918],
       [ 0.69006112,  0.29025531,  0.70824928,  0.75997735,  0.27404494,
         0.52426235,  0.65203378,  0.69602147,  0.30447601,  0.01026291,
         1.06892601,  0.25840503,  1.09526283,  1.05358645,  0.16859787,
         0.40834236,  0.38160135,  0.56656593,  0.28275844,  0.24284512,
         0.6999108 ,  0.19578894,  0.71938882,  0.74362283,  0.09395322,
         0.30249776,  0.39939118,  0.52969471,  0.07290873,  0.05090927],
       [ 0.77690115,  0.26011456,  0.78483708,  0.86618251,  0.23912064,
         0.43114332,  0.62411835,  0.69568427,  0.22221036, -0.13050696,
         1.07244771,  0.14656856,  1.05358645,  1.15675108,  0.10761767,
         0.26507336,  0.27901503,  0.41034892,  0.16129717,  0.11272819,
         0.78224906,  0.18583878,  0.78093517,  0.85345782,  0.10247735,
         0.23889831,  0.36727279,  0.52047264,  0.04226056, -0.02915949],
       [-0.2063214 ,  0.03063436, -0.18371802, -0.14548911,  0.32785767,
         0.18535788,  0.14201258,  0.06022815,  0.18574813,  0.44549907,
         0.17878461,  0.39627834,  0.16859787,  0.10761767,  1.07751717,
         0.41055483,  0.33021893,  0.37536326,  0.38461567,  0.48881114,
        -0.21876056, -0.0705464 , -0.20134954, -0.16448267,  0.32119614,
        -0.01472397, -0.02067849, -0.07046315, -0.1392265 ,  0.13981477],
       [ 0.15621511,  0.21082466,  0.20098703,  0.1700672 ,  0.28836462,
         0.71462636,  0.63142817,  0.43978373,  0.44420465,  0.56673479,
         0.33407363,  0.27838855,  0.40834236,  0.26507336,  0.41055483,
         1.01150546,  0.80680119,  0.75218878,  0.39971521,  0.79944928,
         0.15244135,  0.15215495,  0.21171964,  0.1549931 ,  0.21136272,
         0.64128164,  0.58965066,  0.43890709,  0.26093497,  0.56376917],
       [ 0.17610741,  0.15617643,  0.21028923,  0.19529587,  0.23393015,
         0.56246186,  0.67492921,  0.42618624,  0.36423127,  0.46617124,
         0.3461626 ,  0.25985608,  0.38160135,  0.27901503,  0.33021893,
         0.80680119,  0.9930894 ,  0.791895  ,  0.2960503 ,  0.79166253,
         0.16298921,  0.10172927,  0.20488857,  0.16994075,  0.14714609,
         0.44430883,  0.59232928,  0.4057696 ,  0.15270994,  0.42179549],
       [ 0.33755715,  0.20536746,  0.37020583,  0.34148374,  0.35126144,
         0.63825733,  0.66274392,  0.58498362,  0.42623579,  0.37187333,
         0.51389   ,  0.28929031,  0.56656593,  0.41034892,  0.37536326,
         0.75218878,  0.791895  ,  1.02254374,  0.32730742,  0.649404  ,
         0.32028902,  0.10886871,  0.35965319,  0.31226904,  0.18933173,
         0.42672349,  0.51241867,  0.56499554,  0.12772436,  0.31223212],
       [-0.05470671,  0.0276119 , -0.03660331, -0.02855368,  0.17464023,
         0.23056655,  0.18520713,  0.12172201,  0.41352353,  0.29819705,
         0.25732432,  0.37814362,  0.28275844,  0.16129717,  0.38461567,
         0.39971521,  0.2960503 ,  0.32730742,  0.94208983,  0.35176439,
        -0.08461885, -0.05755568, -0.06349226, -0.07582767, -0.02244645,
         0.09324909,  0.05586795,  0.01557774,  0.38871066,  0.09573303],
       [-0.07733353,  0.04454648, -0.03990853, -0.04810519,  0.27353818,
         0.49934573,  0.45420151,  0.23070027,  0.36414104,  0.71982158,
         0.20924093,  0.31387651,  0.24284512,  0.11272819,  0.48881114,
         0.79944928,  0.79166253,  0.649404  ,  0.35176439,  1.00543438,
        -0.07145856, -0.01478242, -0.03060993, -0.04910151,  0.16823823,
         0.37003872,  0.37390307,  0.19862936,  0.10222797,  0.58803248],
       [ 0.96609436,  0.32768557,  0.96244342,  0.97261522,  0.18109405,
         0.47183557,  0.64637162,  0.79458949,  0.19321211, -0.30535206,
         0.73216056, -0.07657658,  0.6999108 ,  0.78224906, -0.21876056,
         0.15244135,  0.16298921,  0.32028902, -0.08461885, -0.07145856,
         0.98790133,  0.33960842,  0.97307455,  0.98023418,  0.18794657,
         0.40229968,  0.52821929,  0.74211745,  0.2525298 ,  0.03422968],
       [ 0.27690276,  0.86990512,  0.28254774,  0.2672589 ,  0.06053394,
         0.23668102,  0.28080591,  0.28465108,  0.12814767, -0.05698393,
         0.19055662,  0.40229557,  0.19578894,  0.18583878, -0.0705464 ,
         0.15215495,  0.10172927,  0.10886871, -0.05755568, -0.01478242,
         0.33960842,  0.96024893,  0.34597588,  0.3234255 ,  0.22968603,
         0.34021322,  0.33710866,  0.36324226,  0.24540776,  0.17734954],
       [ 0.95387212,  0.33536433,  0.95579395,  0.96133028,  0.20503795,
         0.52435755,  0.68293394,  0.81397905,  0.2250222 , -0.25409728,
         0.73159432, -0.06444996,  0.71938882,  0.78093517, -0.20134954,
         0.21171964,  0.20488857,  0.35965319, -0.06349226, -0.03060993,
         0.97307455,  0.34597588,  0.97103476,  0.96557624,  0.20788414,
         0.45440073,  0.56903451,  0.76673174,  0.27399401,  0.08134591],
       [ 0.94820359,  0.31806668,  0.94560355,  0.98203995,  0.18259017,
         0.45527841,  0.6452562 ,  0.78444378,  0.18324616, -0.28005714,
         0.77872973, -0.0544205 ,  0.74362283,  0.85345782, -0.16448267,
         0.1549931 ,  0.16994075,  0.31226904, -0.07582767, -0.04910151,
         0.98023418,  0.3234255 ,  0.96557624,  1.00668221,  0.1887485 ,
         0.37259344,  0.50547655,  0.71090149,  0.21137657,  0.02566891],
       [ 0.08513255,  0.08419462,  0.11627625,  0.09705681,  0.79263236,
         0.55466282,  0.43151243,  0.43749099,  0.40970577,  0.5271188 ,
         0.11139074, -0.04924597,  0.09395322,  0.10247735,  0.32119614,
         0.21136272,  0.14714609,  0.18933173, -0.02244645,  0.16823823,
         0.18794657,  0.22968603,  0.20788414,  0.1887485 ,  1.01856696,
         0.55386819,  0.50564223,  0.54302589,  0.48340875,  0.62464624],
       [ 0.34206754,  0.25700589,  0.38219609,  0.32730542,  0.4443013 ,
         0.78947922,  0.67419801,  0.59031811,  0.46456611,  0.44420196,
         0.24548957, -0.03637376,  0.30249776,  0.23889831, -0.01472397,
         0.64128164,  0.44430883,  0.42672349,  0.09324909,  0.37003872,
         0.40229968,  0.34021322,  0.45440073,  0.37259344,  0.55386819,
         0.89386219,  0.79085375,  0.73071381,  0.58596959,  0.72894862],
       [ 0.48499403,  0.26732972,  0.51970045,  0.4796498 ,  0.41470649,
         0.75378288,  0.81420796,  0.69864752,  0.433057  ,  0.32817009,
         0.36405601, -0.01859953,  0.39939118,  0.36727279, -0.02067849,
         0.58965066,  0.59232928,  0.51241867,  0.05586795,  0.37390307,
         0.52821929,  0.33710866,  0.56903451,  0.50547655,  0.50564223,
         0.79085375,  0.88544765,  0.79036849,  0.50292439,  0.61113095],
       [ 0.70016541,  0.29373954,  0.72557376,  0.68949475,  0.47956708,
         0.76086753,  0.80766051,  0.8582352 ,  0.45106913,  0.16239987,
         0.5120714 , -0.0647622 ,  0.52969471,  0.52047264, -0.07046315,
         0.43890709,  0.4057696 ,  0.56499554,  0.01557774,  0.19862936,
         0.74211745,  0.36324226,  0.76673174,  0.71090149,  0.54302589,
         0.73071381,  0.79036849,  0.9462611 ,  0.51681606,  0.46966056],
       [ 0.17562161,  0.1086933 ,  0.19614998,  0.15092191,  0.36034081,
         0.47210708,  0.37982762,  0.37071386,  0.67165277,  0.28880029,
         0.06511046, -0.08925726,  0.07290873,  0.04226056, -0.1392265 ,
         0.26093497,  0.15270994,  0.12772436,  0.38871066,  0.10222797,
         0.2525298 ,  0.24540776,  0.27399401,  0.21137657,  0.48340875,
         0.58596959,  0.50292439,  0.51681606,  1.0164073 ,  0.51536721],
       [-0.0539932 ,  0.0767202 , -0.0110691 , -0.05286682,  0.49763871,
         0.64251402,  0.46652163,  0.31831904,  0.43861648,  0.78387159,
         0.00662041, -0.00528918,  0.05090927, -0.02915949,  0.13981477,
         0.56376917,  0.42179549,  0.31223212,  0.09573303,  0.58803248,
         0.03422968,  0.17734954,  0.08134591,  0.02566891,  0.62464624,
         0.72894862,  0.61113095,  0.46966056,  0.51536721,  0.94238952]])

In [8]:
# Eigenvalues and Eigenvectors
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
eigen_values

array([1.28157816e+01, 5.97687688e+00, 2.91560865e+00, 1.87285665e+00,
       1.55385380e+00, 1.24564838e+00, 7.08850932e-01, 5.02973799e-01,
       3.80844891e-01, 3.52364097e-01, 3.07194968e-01, 2.58836576e-01,
       2.37568155e-01, 1.51134894e-01, 8.44288432e-02, 6.68061084e-02,
       6.23649419e-02, 5.43078396e-02, 5.03510677e-02, 1.16910214e-04,
       7.65551213e-04, 1.48174916e-03, 7.44399161e-03, 6.40611682e-03,
       1.45925577e-02, 1.75539947e-02, 3.08311183e-02, 2.27601049e-02,
       2.67900216e-02, 2.62220075e-02])

In [9]:
eigen_vectors

array([[ 2.22655949e-01,  2.29404474e-01,  2.09176562e-02,
        -3.53824504e-02,  6.17617311e-02, -2.33506704e-02,
         1.65615176e-01,  3.69719584e-02, -1.99873478e-01,
         1.77846023e-02, -6.48481516e-02, -5.66613377e-02,
         1.25627937e-02,  7.76175307e-02, -1.17316828e-01,
        -2.15156930e-02,  1.75794108e-01, -2.37849078e-01,
        -1.95860521e-01,  6.92032346e-01,  2.41266704e-01,
         1.99410007e-01, -1.78680559e-01, -9.52807480e-03,
        -3.70695014e-02, -1.88163416e-01,  1.48213480e-02,
        -7.26616504e-02,  1.18104266e-01,  6.24373773e-02],
       [ 1.05219347e-01,  3.92441018e-02, -3.67067393e-02,
         6.11433527e-01, -4.85914894e-02,  8.06393591e-02,
        -2.98273622e-02,  4.96764288e-02,  1.96767408e-01,
         1.86939939e-02, -2.71271273e-01, -3.53317726e-01,
         2.38191469e-01,  8.54854553e-03, -1.22550702e-01,
        -1.49196176e-01, -1.93715973e-02, -9.55942640e-02,
         1.97413777e-02,  1.29930978e-03, -1.32907599e-02,
        -4.21751547e-04, -2.53045678e-02, -5.62579517e-03,
         1.39004012e-01,  8.02581207e-02,  1.25319718e-01,
        -3.18082731e-01, -3.26671330e-01, -9.10018936e-02],
       [ 2.30670082e-01,  2.10680798e-01,  2.15142128e-02,
        -3.72267839e-02,  6.14698139e-02, -1.89369152e-02,
         1.53741142e-01,  2.87255852e-02, -1.94589501e-01,
        -3.18266083e-03, -8.30525074e-02, -3.76228370e-02,
         3.76065031e-02,  5.59340959e-02, -1.04856461e-01,
         2.74832142e-03,  1.65789170e-01, -2.27825982e-01,
        -2.13516227e-01, -6.96888891e-01,  3.83531199e-01,
         2.02588192e-02, -1.70774973e-01,  7.51557820e-03,
         6.10310400e-03, -1.16981685e-01, -6.66112859e-03,
        -1.11939129e-02,  6.48643628e-02,  6.90191508e-02],
       [ 2.29599682e-01,  2.29334833e-01, -1.72672775e-02,
        -5.43609136e-02,  2.44956563e-02,  2.62825250e-03,
         1.03259115e-01,  8.64892478e-02, -2.04456641e-01,
         6.34087440e-02, -1.57117730e-02, -5.76632852e-02,
         6.97275690e-02,  3.61268579e-02, -4.63786273e-02,
        -5.17309077e-03,  3.74109378e-01, -4.39205695e-02,
        -9.67355191e-02, -2.58463038e-02, -4.64296708e-01,
        -2.13901421e-01,  5.64134681e-01,  1.01195522e-01,
        -1.97010174e-01,  1.22736746e-01,  5.39080526e-02,
        -7.34015884e-02, -2.49013991e-03,  1.05084738e-01],
       [ 1.36608215e-01, -1.81330675e-01,  1.24075722e-01,
        -1.57793789e-01, -3.84643658e-01,  2.23208438e-01,
         1.07394965e-01, -3.22430801e-01, -5.93226920e-02,
        -2.08863642e-01,  1.05019576e-02, -2.02953060e-01,
         1.25472356e-01,  4.93612247e-01, -1.18116261e-01,
         1.33697528e-02, -2.95542773e-02, -1.86165230e-01,
         4.07181923e-01, -4.76775956e-03,  1.54697245e-03,
         7.08597377e-03,  2.15290589e-02,  5.87868789e-02,
         1.10051643e-02,  7.87393013e-02, -6.89041283e-03,
         3.87536912e-02,  1.09230933e-01,  8.83241176e-02],
       [ 2.29307654e-01, -1.62642462e-01,  7.82840837e-02,
        -4.16161228e-02,  2.00949162e-02,  2.54891381e-02,
        -1.93380184e-02, -8.58309014e-02, -9.24225920e-02,
        -2.33284638e-01, -3.23375918e-01,  9.87056936e-02,
         1.53954760e-01, -2.62605603e-02,  2.20252370e-01,
         9.72360989e-02, -1.02373958e-01, -9.48794134e-02,
        -2.30677610e-01,  4.40258633e-02, -3.72537469e-02,
         1.07518446e-03,  2.74355219e-01, -7.03163680e-02,
         3.66101248e-01, -2.08919236e-01, -3.92628387e-01,
         2.55843242e-01, -1.91872252e-01, -2.33092964e-01],
       [ 2.54257744e-01, -6.80139922e-02,  5.36495799e-03,
        -3.03655761e-02,  9.63975797e-02,  3.30403161e-02,
         7.70625080e-02, -8.51278411e-02, -1.99307141e-02,
        -5.16629447e-02,  1.92730343e-01,  3.74470896e-02,
         4.13738993e-01, -2.64282322e-01, -4.96474266e-02,
         1.67690112e-01, -1.07949991e-01,  8.55501764e-02,
         9.07209003e-03,  2.82979436e-02, -2.35862125e-02,
         2.75551238e-02, -1.93619284e-01,  6.31321151e-01,
        -1.57992617e-01,  2.62669479e-02,  1.45480944e-01,
         2.14214131e-01, -2.02684662e-01, -4.44138387e-02],
       [ 2.57849975e-01,  2.65829475e-02,  4.76097049e-02,
        -6.26126820e-02, -3.36355460e-02,  3.88499136e-02,
         1.71892760e-01, -1.25072092e-01, -8.13518377e-02,
        -1.04652211e-01, -4.10571517e-02, -5.23836118e-02,
         1.26244068e-01, -2.68012857e-01, -1.05070679e-01,
         3.75390521e-01, -1.46862389e-01,  2.13147316e-01,
         3.16111289e-02,  1.15842999e-03,  7.83298653e-03,
         1.49955134e-02, -4.20331293e-03, -6.03982163e-01,
        -1.72971454e-01,  1.44469411e-01,  2.98179800e-01,
        -2.19785175e-02,  4.55594900e-02, -2.04212800e-01],
       [ 1.42882982e-01, -1.80462371e-01,  5.73955900e-02,
        -2.65221835e-02, -2.31230957e-01, -3.76003699e-01,
         9.37074357e-02, -3.37488496e-01,  8.31138302e-02,
         5.67617301e-01, -3.00755746e-01,  2.41360615e-01,
         1.59170756e-01, -7.61245546e-03, -1.32490882e-01,
        -2.44307616e-01,  2.56650135e-02,  1.60574374e-01,
        -6.02897410e-02, -2.34315101e-03, -5.95031060e-03,
         1.67706162e-03, -1.72317917e-02, -1.46711920e-03,
        -2.42978927e-02,  1.78372678e-02, -1.69048443e-02,
         1.94455269e-02,  1.13946266e-01,  8.81592898e-03],
       [ 5.46443401e-02, -3.72086671e-01,  1.65673098e-02,
        -8.57800995e-02, -7.13132836e-02,  1.24308752e-01,
        -2.65001182e-01, -8.91626497e-02, -2.52053014e-01,
         8.31899955e-03, -1.37156167e-01, -2.76190560e-01,
         6.76908472e-02, -3.21006046e-01,  5.00236848e-01,
        -8.71493734e-02,  1.95694755e-01, -2.08475380e-02,
        -4.26774284e-02, -6.89509277e-03,  3.39547714e-03,
        -1.39904882e-02, -1.49684998e-01, -2.24509681e-02,
        -1.58580224e-01, -4.62657199e-02,  2.97026947e-02,
        -2.40761166e-01,  1.16711570e-01,  2.54150112e-01],
       [ 2.22084497e-01,  1.14349122e-01, -2.69018331e-01,
        -8.96847707e-02, -1.93414654e-01,  1.12267764e-02,
        -3.19320876e-01, -2.79775563e-02,  1.77689385e-01,
         2.81169997e-02,  5.67455265e-02,  4.37108963e-03,
        -5.85523223e-02,  6.13216847e-04, -2.21016094e-02,
         4.13856226e-03, -3.59267383e-01, -1.14346869e-01,
        -2.12447562e-02, -1.02137404e-02,  8.58517335e-02,
        -2.10370319e-01,  2.06478156e-01,  9.20792610e-02,
        -2.42800373e-01, -5.05784610e-01,  9.44374049e-02,
        -2.32318010e-01,  1.43260761e-01, -1.83688177e-01],
       [ 3.52051230e-02, -9.35772016e-02, -3.16194220e-01,
         3.63017346e-01, -1.99626124e-01, -1.53414511e-02,
         7.36169305e-02, -2.93303419e-01, -4.72386205e-01,
        -9.18548909e-02,  2.78503614e-01,  4.14004702e-01,
        -2.35374479e-01, -4.17516604e-02,  3.03422173e-02,
        -1.52391623e-02,  4.37833166e-02, -7.46432143e-02,
         1.32289634e-02,  8.40927487e-04, -1.30661306e-02,
        -4.62001853e-03, -2.27212659e-02,  1.09436864e-03,
         8.56975175e-02,  2.42127681e-02,  4.55462083e-02,
        -1.68763916e-01, -1.91142895e-01, -6.68455657e-02],
       [ 2.25763213e-01,  9.31404002e-02, -2.72784430e-01,
        -7.72505438e-02, -1.47647305e-01, -9.31828377e-03,
        -3.51214684e-01, -4.24600919e-02,  2.01072455e-01,
        -9.92003131e-02, -4.48227717e-02,  7.88668578e-02,
        -7.85769183e-02, -7.72005370e-02, -3.62448526e-02,
         6.33920652e-03, -1.50598407e-01, -2.27092495e-01,
        -2.60411845e-01,  1.27845289e-02,  2.34348458e-02,
         2.62730684e-01,  7.15171973e-02,  8.21359641e-03,
         1.22160636e-01,  5.38483328e-01,  8.85948994e-02,
         1.39935637e-01,  8.80351635e-02,  2.89640246e-01],
       [ 2.21917399e-01,  1.61824592e-01, -2.28757164e-01,
        -1.14406151e-01, -1.76611758e-01,  4.60361647e-02,
        -3.60059976e-01,  7.41771517e-02,  1.59678478e-01,
         7.07025954e-02,  9.85175625e-02,  6.67768380e-02,
         1.00592542e-01,  5.54173498e-02, -6.08232306e-02,
         1.68704250e-01,  5.22656886e-01,  2.21006799e-01,
         2.02591673e-01,  3.30700646e-03, -7.80704426e-02,
        -3.03087240e-02, -3.05045866e-01, -1.43921814e-01,
         1.40194482e-01, -1.06015256e-01, -2.12410054e-01,
         5.20856996e-02, -1.81936854e-01, -7.07431752e-02],
       [ 2.68982315e-02, -2.07082029e-01, -3.10815423e-01,
        -4.22115143e-02, -2.76929093e-01,  2.90393702e-01,
         4.06610301e-01,  5.36520176e-01,  6.40946271e-02,
         2.02617943e-01, -1.21408620e-01,  1.67347939e-01,
         5.31146520e-02, -2.18096622e-01,  2.20464989e-02,
         2.74592603e-02, -3.57336089e-02, -2.15920197e-01,
         1.90546376e-01, -4.90449764e-04,  6.08302298e-03,
         1.45059943e-02,  3.42414461e-03, -5.71776181e-03,
         1.70383430e-02,  2.20154232e-02, -9.29162842e-02,
         3.90254110e-02,  9.39698504e-02,  2.52075376e-03],
       [ 1.64495883e-01, -2.41723827e-01, -1.61598044e-01,
         4.62350884e-02,  2.69360511e-01, -6.15128505e-02,
        -1.02863496e-02,  2.10487042e-01,  2.08656625e-02,
        -1.27963908e-01, -2.83511534e-01,  2.78442917e-01,
         5.80098919e-03,  4.43076425e-01,  1.56988256e-01,
         1.64743153e-01,  3.75637546e-02,  2.41285774e-01,
         2.14630050e-02,  2.31186945e-04, -8.02538881e-04,
        -2.11975095e-02, -2.80991420e-02,  7.21256706e-02,
         1.21500536e-01, -9.35535819e-02,  4.61127660e-01,
        -7.34708117e-02,  8.86281765e-02,  1.63449314e-01],
       [ 1.53923700e-01, -2.02542262e-01, -2.00423815e-01,
         7.36986110e-03,  3.51096656e-01, -7.28344433e-03,
         1.07139726e-01, -9.57780996e-02,  1.96252999e-01,
         1.54821208e-01,  4.60402303e-01, -8.82850712e-02,
         2.40224721e-01,  1.73009818e-01,  2.29861623e-01,
        -1.20757884e-01,  9.72885370e-02, -1.61415117e-01,
        -8.60055588e-02, -1.01361890e-02,  2.13318499e-02,
         1.75840287e-02,  4.19204166e-02, -1.18121661e-01,
         1.15299764e-01,  1.70245164e-01, -6.91245343e-02,
        -1.13796395e-01,  2.76870513e-01, -3.42958975e-01],
       [ 1.85208258e-01, -1.46886248e-01, -2.27055839e-01,
        -2.91019083e-02,  1.95634939e-01,  1.37250998e-02,
         2.88177044e-01, -2.91167835e-01,  3.68589443e-01,
        -1.05354947e-01, -1.36530340e-01, -1.75656714e-01,
        -5.13984368e-01, -1.11090700e-01,  2.14476324e-02,
        -1.01075109e-01,  1.98456347e-01, -6.69917607e-02,
         6.15033052e-02, -8.28923843e-04, -2.78585977e-02,
        -2.40760415e-02, -3.33761605e-02,  1.08257398e-02,
        -2.02032999e-01, -1.04530047e-01,  3.95362998e-02,
         2.29145486e-01, -2.13052365e-01,  1.83027748e-02],
       [ 5.26243765e-02, -1.52599766e-01, -2.41497848e-01,
        -1.09571034e-02, -2.32153833e-01, -5.39107316e-01,
         1.15015041e-01,  2.66604570e-01, -1.04148940e-01,
        -4.26991672e-01,  1.06868037e-01, -2.94148644e-01,
         5.98535253e-02, -2.36044421e-02, -1.25678539e-01,
        -2.75210647e-01, -3.28364486e-03,  2.59756378e-01,
        -7.07860191e-02, -2.75142379e-03, -2.24983513e-03,
        -9.54473163e-03, -2.17056230e-02, -3.33913136e-03,
        -1.40059196e-03, -1.13264084e-02, -7.99660752e-02,
         7.71273075e-02,  1.15812309e-01, -3.01444379e-02],
       [ 1.00983919e-01, -2.87196746e-01, -2.21422920e-01,
        -3.11908872e-02,  2.42696891e-01,  4.54969220e-02,
        -1.01950491e-01,  7.09743367e-02, -2.92042933e-01,
         3.49630112e-01,  4.53852997e-02, -3.04572398e-01,
        -1.35558927e-01,  1.89127985e-01, -3.20711173e-01,
         2.44514175e-01, -2.63919859e-01,  1.24849160e-01,
        -7.99668290e-02,  2.89990143e-03, -6.13385807e-03,
         1.25312224e-02,  6.92933635e-03, -3.53730708e-02,
        -6.55686705e-02,  3.78810162e-02, -3.07630072e-01,
        -1.65420508e-02, -1.86371846e-01,  1.82364327e-01],
       [ 2.29311508e-01,  2.12533474e-01,  6.49592691e-02,
        -1.15243975e-02,  1.82165603e-02,  1.48821920e-03,
         5.27700652e-02,  6.28963211e-02, -1.19479976e-01,
         9.59766355e-02,  3.15321477e-03, -7.01667873e-02,
        -1.46474324e-01,  6.22135088e-02,  1.76100597e-01,
        -1.73978736e-01, -2.62354698e-01,  8.19694270e-03,
         9.15512940e-02, -1.41453998e-01, -5.79575080e-01,
         4.75753023e-01, -2.70847610e-01, -1.41537957e-02,
         6.71314977e-02, -1.62065659e-01,  2.13277909e-02,
         1.64212957e-03,  6.85220034e-02, -8.22995140e-02],
       [ 1.04381098e-01,  2.78282269e-02,  7.75964908e-02,
         6.35573217e-01, -8.30980847e-02,  8.37545135e-02,
        -5.57812795e-02, -1.23954814e-03,  4.54438217e-02,
         4.59833367e-02,  7.33702676e-02, -4.30549745e-02,
        -3.61245241e-02,  3.38620343e-02,  1.00838664e-01,
         1.92245902e-01,  4.59878762e-02,  1.31816794e-01,
        -1.80083619e-02, -1.73444466e-03,  2.31912599e-02,
         2.45932031e-04,  4.64209093e-02, -4.57633037e-03,
        -1.86141724e-01, -1.07944891e-01, -1.63258329e-01,
         4.28392695e-01,  4.48058933e-01,  1.43403418e-01],
       [ 2.36584683e-01,  1.90605858e-01,  6.49093063e-02,
        -8.32278761e-03,  3.31433441e-02, -2.74242047e-03,
         3.60449950e-02,  5.78252023e-02, -9.92510691e-02,
         5.01489344e-02, -3.24668001e-02, -1.87667209e-02,
        -1.22056863e-01,  3.70283003e-02,  1.66489594e-01,
        -1.55912322e-01, -2.40115361e-01, -3.89329064e-02,
         2.70259154e-02,  1.01719705e-01, -5.35245966e-02,
        -7.27487922e-01, -3.46129011e-01, -2.99577493e-02,
         1.42935932e-01,  2.34547156e-01, -2.95236339e-02,
         1.20821564e-01,  2.62307760e-02,  3.06896529e-02],
       [ 2.29664763e-01,  2.13263241e-01,  2.86101670e-02,
        -2.87972504e-02, -1.19991151e-02,  3.48606260e-02,
        -1.02820745e-02,  1.06643453e-01, -1.26503539e-01,
         1.62100551e-01,  4.19284882e-02, -6.70941882e-02,
        -1.09273847e-01,  4.39392047e-02,  3.37357817e-01,
        -2.27394414e-01, -6.42616907e-02,  3.28171444e-01,
         3.20300393e-01,  3.24728289e-02,  4.69656688e-01,
         1.92858187e-01,  3.21635789e-01,  5.54398071e-02,
        -3.17582953e-02,  1.59642374e-01,  6.53359624e-03,
         7.64988058e-02, -2.03193618e-01, -7.68997009e-02],
       [ 1.22393541e-01, -1.77180644e-01,  2.83640563e-01,
        -4.43512332e-02, -3.46219208e-01,  3.25139181e-01,
         1.07374770e-01,  1.32628994e-01,  1.63221224e-01,
         4.14321033e-02,  2.66363006e-01,  8.19010714e-03,
        -1.59563295e-01,  1.75890513e-01,  1.77867216e-02,
        -1.04651699e-01,  3.19800761e-02,  2.64020014e-01,
        -5.72162576e-01,  3.09036387e-03,  1.05771514e-03,
        -7.75102028e-03, -4.29986286e-02, -7.15885203e-03,
        -2.30429207e-02, -2.18640496e-02,  1.05060019e-01,
        -4.84283387e-02, -1.85162920e-01, -2.67773248e-02],
       [ 1.91616367e-01, -1.51784264e-01,  2.26345860e-01,
         6.99400164e-02,  1.27466796e-01, -2.53934281e-02,
        -1.52396545e-01,  1.77524383e-01,  3.61861340e-02,
        -2.26008138e-01, -1.45531346e-01,  3.27254365e-01,
        -5.91742086e-02,  1.04634342e-01, -8.64398493e-02,
        -1.17808890e-01,  7.94820643e-03, -7.99522031e-02,
         6.98819778e-02, -1.02174299e-02, -3.80116354e-04,
         5.78633496e-02, -1.23785925e-01, -2.48654152e-03,
        -5.46040993e-01,  2.49684427e-01, -3.41863554e-01,
        -2.04175397e-01, -2.04136796e-02, -2.15464291e-01],
       [ 2.16423489e-01, -1.01187190e-01,  1.69217766e-01,
         4.29595310e-02,  1.88202581e-01,  1.46241247e-02,
        -1.58124374e-02,  4.89373567e-02,  1.11237566e-01,
        -8.20784315e-02,  3.02412901e-01,  2.12021706e-01,
         2.00454663e-01, -1.36193751e-01, -1.47621936e-01,
        -3.19182207e-01, -9.54294648e-02, -7.25579998e-02,
         1.71800766e-01, -2.41262482e-03, -5.72736687e-03,
        -1.94924069e-02,  1.07444866e-01, -3.11086992e-01,
         5.76611826e-02, -2.51653050e-01, -1.39206950e-02,
         2.86174186e-02, -1.57212431e-01,  5.39664262e-01],
       [ 2.44611503e-01, -7.48004107e-03,  1.88200516e-01,
        -3.03224599e-04,  5.20810239e-02,  2.42326922e-02,
         1.27686843e-01, -6.32847727e-02,  1.40975718e-01,
        -1.01950078e-01,  2.13444351e-02,  4.53878519e-03,
        -2.56545406e-01, -2.63495225e-01, -1.56385370e-01,
         1.75505158e-01,  1.65530317e-02,  2.41886417e-01,
         1.15563931e-01, -3.38195455e-03,  3.35688061e-02,
         1.85707930e-03,  7.42302753e-02,  2.54456140e-01,
         3.82941172e-01,  4.76241700e-02, -2.21738717e-01,
        -4.61483180e-01,  3.12859304e-01,  8.58352994e-02],
       [ 1.19424971e-01, -1.26062501e-01,  3.02631904e-01,
         4.89446709e-02, -1.74072342e-01, -5.26029741e-01,
         3.78749289e-03,  1.87575059e-01,  1.14104244e-01,
         1.50281602e-01,  1.95389167e-01, -7.20015138e-02,
        -1.61608373e-01,  3.76525069e-02,  2.25008869e-01,
         4.19209533e-01,  2.41889510e-02, -3.62213629e-01,
         9.98669885e-02,  2.46810023e-03,  1.11728662e-02,
         7.17270923e-03,  2.99796782e-02,  3.91816043e-04,
         1.92964008e-02, -1.77736279e-03,  7.84486235e-02,
        -4.25104218e-02, -2.18952744e-01,  4.09303504e-02],
       [ 1.15314915e-01, -2.80037709e-01,  2.15835691e-01,
         1.19078758e-02,  7.24566375e-02,  8.33420698e-02,
        -3.29232832e-01,  1.61518956e-01, -2.02571081e-01,
         8.72943656e-02,  1.24078298e-02, -5.54762549e-02,
        -2.18749214e-01, -1.65797113e-01, -3.51338432e-01,
        -1.94493836e-01,  1.61004332e-01, -1.50315784e-01,
         1.21619068e-01,  1.09400181e-03,  1.48732308e-02,
        -1.41536486e-02,  6.83793681e-02,  4.13811505e-02,
         2.04246948e-01, -1.95624448e-02,  3.34103731e-01,
         2.63460068e-01,  1.38409213e-01, -3.37594760e-01]])

**CASE 1: Without PCA**

In [10]:
# Model training
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [11]:
y_pred = model.predict(X_test)
print("Accuracy without PCA:", accuracy_score(y_test, y_pred))
print("Model Report")
print(classification_report(y_test, y_pred, zero_division=1))

Accuracy without PCA: 0.9824561403508771
Model Report
              precision    recall  f1-score   support

           0       0.97      0.98      0.98        63
           1       0.99      0.98      0.99       108

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171

**PCA CASE 1: PC1 only**

In [12]:
pca_1 = PCA(n_components=1)

X_train_pca1 = pca_1.fit_transform(X_train)
X_test_pca1 = pca_1.transform(X_test)

model_1 = LogisticRegression(max_iter=5000)
model_1.fit(X_train_pca1, y_train)

y_pred_1 = model_1.predict(X_test_pca1)
acc_1 = accuracy_score(y_test, y_pred_1)

explained_var = pca_1.explained_variance_ratio_
print("Variance: ", explained_var)
print("Accuracy using PC1:", acc_1)
print("Model Report")
print(classification_report(y_test, y_pred_1, zero_division=1))

Variance:  [0.4307302]
Accuracy using PC1: 0.9239766081871345
Model Report
              precision    recall  f1-score   support

           0       0.90      0.89      0.90        63
           1       0.94      0.94      0.94       108

    accuracy                           0.92       171
   macro avg       0.92      0.92      0.92       171
weighted avg       0.92      0.92      0.92       171

**PCA CASE 2: PC1 + PC2**

In [13]:
pca_2 = PCA(n_components=2)

X_train_pca2 = pca_2.fit_transform(X_train)
X_test_pca2 = pca_2.transform(X_test)

explained_var = pca_2.explained_variance_ratio_
print("Variance: ", explained_var)

model_2 = LogisticRegression(max_iter=5000)
model_2.fit(X_train_pca2, y_train)

y_pred_2 = model_2.predict(X_test_pca2)
acc_2 = accuracy_score(y_test, y_pred_2)

print("Accuracy using PC1 + PC2:", acc_2)
print("Model Report")
print(classification_report(y_test, y_pred_2, zero_division=1))

Variance:  [0.4307302 0.200879 ]

Accuracy using PC1 + PC2: 0.9707602339181286
Model Report
              precision    recall  f1-score   support

           0       0.97      0.95      0.96        63
           1       0.97      0.98      0.98       108

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

**PCA CASE 3: PC1 + PC2 + PC3**

In [14]:
pca_3 = PCA(n_components=3)

X_train_pca3 = pca_3.fit_transform(X_train)
X_test_pca3 = pca_3.transform(X_test)

explained_var = pca_3.explained_variance_ratio_
print("Variance: ", explained_var)

model_3 = LogisticRegression(max_iter=5000)
model_3.fit(X_train_pca3, y_train)

y_pred_3 = model_3.predict(X_test_pca3)
acc_3 = accuracy_score(y_test, y_pred_3)

print("Accuracy using PC1 + PC2 + PC3:", acc_3)
print("Model Report")
print(classification_report(y_test, y_pred_3, zero_division=1))

Variance:  [0.4307302  0.200879   0.09799174]
Accuracy using PC1 + PC2 + PC3: 0.9707602339181286
Model Report
              precision    recall  f1-score   support

           0       0.97      0.95      0.96        63
           1       0.97      0.98      0.98       108

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171